platform :ios, '8.0'
use_frameworks!

pod "AFNetworking"
pod 'MJExtension'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'REMenu'
pod 'MJRefresh'
pod 'WebViewJavascriptBridge', '~> 5.0'
pod 'YTKKeyValueStore'
pod 'Masonry'
pod 'ReactiveCocoa'
pod 'FCUUID'